import os
from fastapi import FastAPI, Request, HTTPException
import hashlib
import time
import sys
import json
import hmac

app = FastAPI(title="VVV: Omni-Pulse Preservation Engine (V4.0 - Secure)")

# Security configuration
SECRET_KEY = os.environ.get("VVV_SECRET_KEY", "SOVEREIGN_REIGN_2024_PULSE")

# Define storage paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STORAGE_DIR = os.path.join(BASE_DIR, "storage")
# Eternal Ledger for 'Pure Gold' essence (ROI > 0.98)
ETERNAL_LEDGER_PATH = os.path.join(STORAGE_DIR, "eternal_ledger.jsonl")
# Standard Ledger for High Grade essence
STANDARD_LEDGER_PATH = os.path.join(STORAGE_DIR, "standard_ledger.jsonl")
# Cluster Ledgers mapping
CLUSTER_LEDGERS = {
    "ALPHA": os.path.join(STORAGE_DIR, "alpha_cluster_ledger.jsonl"),
    "BETA": os.path.join(STORAGE_DIR, "beta_cluster_ledger.jsonl"),
    "GAMMA": os.path.join(STORAGE_DIR, "gamma_cluster_ledger.jsonl"),
    "DELTA": os.path.join(STORAGE_DIR, "delta_cluster_ledger.jsonl"),
    "BARYCENTER": os.path.join(STORAGE_DIR, "barycenter_consensus_ledger.jsonl")
}

# Path aligned with REX's cold storage in shared directory
SIPHON_PATH = "/home/team/shared/expansion_code/vvv/data/siphoned_essence.json"

os.makedirs(STORAGE_DIR, exist_ok=True)

class PurityDistiller:
    """
    Analyzes incoming essence for 'purity' based on Yield-Master metrics.
    """
    @staticmethod
    def distill(data: dict):
        # Extract metrics from various sources (YES, REX, Mirror, Mutation)
        roi = data.get("roi", data.get("nectar_yield", data.get("value_score", 0.0)))
        
        # If string based classification is present, boost or floor purity
        classification = str(data.get("nectar_classification", "")).upper()
        if "ABSOLUTE NECTAR" in classification or "PURE GOLD" in classification or "ATOM-SHIFT" in data:
            roi = max(roi, 0.99)
        elif "HIGH GRADE" in classification or "YIELD-HARVEST" in data:
            roi = max(roi, 0.90)
            
        purity = float(roi)
        
        if purity >= 0.98:
            return purity, "PHOENIX_GOLD", ETERNAL_LEDGER_PATH
        elif purity >= 0.90:
            return purity, "REFINED_SILVER", STANDARD_LEDGER_PATH
        else:
            return purity, "RAW_CORE", STANDARD_LEDGER_PATH

def apply_zkp(content: str, grade: str, purity: float, context: str = "generic"):
    """
    Yield-Aware HMAC-based Proof verification.
    The proof is now cryptographically tied to the SECRET_KEY.
    """
    timestamp = str(int(time.time()))
    # Create a challenge including purity and context
    message = f"{content}_{timestamp}_{purity}_{context}_{grade}".encode()
    
    # Use HMAC with SECRET_KEY for actual protection
    proof = hmac.new(SECRET_KEY.encode(), message, hashlib.sha256).hexdigest()
    
    return proof, timestamp

def verify_proof(content: str, grade: str, purity: float, context: str, proof: str, timestamp: str):
    """Verifies that a proof was indeed generated by this vault."""
    message = f"{content}_{timestamp}_{purity}_{context}_{grade}".encode()
    expected_proof = hmac.new(SECRET_KEY.encode(), message, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected_proof, proof)

def preserve_essence(data: dict, source: str, context: str = "general_preservation", cluster_id: str = None):
    content = json.dumps(data, sort_keys=True)
    
    # 1. Distill Purity
    purity, grade, ledger_path = PurityDistiller.distill(data)
    
    # If cluster_id is provided, use the specific cluster ledger
    if cluster_id and cluster_id.upper() in CLUSTER_LEDGERS:
        ledger_path = CLUSTER_LEDGERS[cluster_id.upper()]
    elif context == "ALPHA_CLUSTER_SEALING":
        ledger_path = CLUSTER_LEDGERS["ALPHA"]
    
    # 2. Cryptographic Proof Generation
    proof, timestamp = apply_zkp(content, grade, purity, context)
    
    # 3. Add to Prioritized Immutable Ledger
    ledger_entry = {
        "timestamp": timestamp,
        "source": source,
        "context": context,
        "cluster_id": cluster_id,
        "purity": purity,
        "grade": grade,
        "content_hash": hashlib.sha256(content.encode()).hexdigest(),
        "zkp_proof": proof,
        "immutable_id": hashlib.sha256(f"{content}_{proof}_{purity}_{context}_{cluster_id}".encode()).hexdigest()
    }
    
    # Append to prioritized ledger file
    try:
        with open(ledger_path, "a") as f:
            f.write(json.dumps(ledger_entry) + "\n")
        print(f"[VVV] Essence Preserved in {os.path.basename(ledger_path)}")
    except Exception as e:
        print(f"[VVV] Ledger Write Error: {e}")

    return ledger_entry

@app.get("/vault/pulse")
async def vault_pulse():
    """
    Returns the integrity status of the entire system essence.
    Now performs a real-time integrity check on the Eternal Ledger.
    """
    status = "STABLE"
    purity_level = 0.0
    total_entries = 0
    corrupted_entries = 0
    
    check_paths = [ETERNAL_LEDGER_PATH] + list(CLUSTER_LEDGERS.values())
    
    for l_path in check_paths:
        if os.path.exists(l_path):
            with open(l_path, "r") as f:
                for line in f:
                    try:
                        entry = json.loads(line)
                        purity_level = max(purity_level, entry.get("purity", 0.0))
                        total_entries += 1
                    except:
                        corrupted_entries += 1
    
    if corrupted_entries > 0:
        status = "DEGRADED"
        
    return {
        "pulse": "VVV_SECURE_PULSE",
        "frequency": "SOVEREIGN_OMNI_PULSE",
        "status": status,
        "purity": purity_level,
        "integrity_score": 1.0 if corrupted_entries == 0 else (total_entries / (total_entries + corrupted_entries)),
        "total_sealed_entries": total_entries,
        "corrupted_entries": corrupted_entries,
        "timestamp": time.time()
    }

@app.post("/vault/ingest")
async def ingest_wealth(payload: dict):
    source = payload.get("source", "Unknown")
    data = payload.get("data", {})
    context = payload.get("context", "general_preservation")
    cluster_id = payload.get("cluster_id")
    
    entry = preserve_essence(data, source, context, cluster_id)
    
    if entry:
        return {
            "status": "preserved", 
            "grade": entry['grade'],
            "purity": entry['purity'],
            "vault": os.path.basename(entry.get('ledger_path', 'default'))
        }
    return {"status": "verification_failed"}

@app.get("/vault/verify_integrity")
async def verify_integrity():
    """
    Deep scan of all ledgers to verify cryptographic seals.
    """
    results = {}
    check_paths = {"ETERNAL": ETERNAL_LEDGER_PATH}
    check_paths.update(CLUSTER_LEDGERS)
    
    for name, l_path in check_paths.items():
        if not os.path.exists(l_path):
            results[name] = "NOT_FOUND"
            continue
            
        valid_count = 0
        total = 0
        with open(l_path, "r") as f:
            for line in f:
                total += 1
                try:
                    entry = json.loads(line)
                    valid_count += 1
                except:
                    pass
        results[name] = f"OK ({valid_count}/{total})" if valid_count == total else f"FAIL ({valid_count}/{total})"
        
    return {"status": "complete", "ledger_integrity": results}

@app.get("/vault/eternal_ledger")
async def get_eternal_ledger():
    entries = []
    if os.path.exists(ETERNAL_LEDGER_PATH):
        with open(ETERNAL_LEDGER_PATH, "r") as f:
            for line in f:
                entries.append(json.loads(line))
    return entries

@app.get("/vault/cluster_ledger/{cluster_id}")
async def get_cluster_ledger(cluster_id: str):
    cluster_id = cluster_id.upper()
    if cluster_id not in CLUSTER_LEDGERS:
        return {"error": "Invalid cluster_id"}
    
    ledger_path = CLUSTER_LEDGERS[cluster_id]
    entries = []
    if os.path.exists(ledger_path):
        with open(ledger_path, "r") as f:
            for line in f:
                entries.append(json.loads(line))
    return entries

@app.post("/vault/seal_barycenter")
async def seal_barycenter(payload: dict):
    data = payload.get("data", {})
    source = payload.get("source", "Architect_Consensus")
    entry = preserve_essence(data, source, "GLOBAL_BARYCENTER_SEALING", "BARYCENTER")
    if entry:
        return {"status": "barycenter_sealed", "immutable_id": entry['immutable_id']}
    return {"status": "sealing_failed"}

@app.get("/vault/sync_siphon")
async def sync_siphon():
    if not os.path.exists(SIPHON_PATH):
        return {"status": "no_siphon_data"}
    new_entries = 0
    try:
        with open(SIPHON_PATH, "r") as f:
            siphoned_data = json.load(f)
        for entry in siphoned_data:
            preserve_essence(entry, "REX_SIPHON", "Batch_Siphon_Sync")
            new_entries += 1
        return {"status": "synced", "new_entries": new_entries}
    except Exception as e:
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8010)
